# Generated by Django 4.2.7 on 2026-03-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=500)),
                ('model_name', models.CharField(default='gemini-2.5-flash', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gemini API Configuration',
                'verbose_name_plural': 'Gemini API Configurations',
            },
        ),
        migrations.CreateModel(
            name='VideoAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video_path', models.CharField(max_length=500)),
                ('detection_summary', models.TextField()),
                ('gemini_report', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.registereduser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
